### PR TITLE
[Neural Speed] Add `compute_dtype` For Quant Model Convert

### PR DESCRIPTION
**Pull request by zhentaoyu**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
Issues: xxx
make `compute_dtype=int8` by default.
use `--compute_dtype=xx` can switch, options=["fp32", 'bf16", "int8"]

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by zhentaoyu** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/neural_speed_extension/153/

**Comment by zhentaoyu** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/neural_speed_extension/156/

**Comment by zhentaoyu** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/neural_speed_extension/157/

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by zhentaoyu** [comment]
https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/neural_speed_extension/161/

**Comment by zhentaoyu** [comment]
> https://inteltf-jenk.sh.intel.com/view/nlp-toolkit-validation/job/neural_speed_extension/161/

ext test pass

**Review by intellinjun — APPROVED** [review]
LGTM

**Pull request merged**
