### PR TITLE
XeTLA INT4 With BF16 Support

### PR DESCRIPTION
**Pull request by DDEle**
## Type of Change: Feature
API not changed

## Description
1. Fix int4 compile error for bf16 (initially as part of #297)
2. Rename quant_mode, including removing "fullrange" which caused misunderstanding.

## Expected Behavior & Potential Risk
N/A

## How has this PR been tested?
N/A

## Dependency Change?
N/A

### CODE REVIEW

**Review by zhewang1-intc — APPROVED** [review]
LGTM

**Review by airMeng — APPROVED** [review]

**Comment by airMeng** [comment]
@xiaowangintel

**Comment by zhewang1-intc** [comment]
> @xiaowangintel

for fp zero section pls refer to this [PR](https://github.com/intel/neural-speed/pull/297)

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by DDEle** [comment]
Ready to merge as internal IPEX PR merged.

**Pull request merged**
