### PR TITLE
Python API extension tests for GPTQ

### PR DESCRIPTION
**Pull request by Zhenzhong1**
## Type of Change

feature or bug fix or documentation or others
API changed or not

## Description

detail description 
Issues: xxx

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

### CODE REVIEW

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/86/

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/87/

**Comment by VincyZhang** [comment]
corresponding val branch：https://github.com/intel-innersource/frameworks.ai.lpot.lpot-validation/pull/614

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/96/

**Comment by Zhenzhong1** [comment]
https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/98/

**Pull request merged**
