### PR TITLE
add tests and nodes

### PR DESCRIPTION
**Pull request by VincyZhang**
## Type of Change

add CI for bestla, add SPR nodes for UT

### CODE REVIEW

**Review by airMeng — APPROVED** [review]

**Comment by airMeng** [comment]
https://github.com/intel/neural-speed/actions/runs/7418532866/job/20186610889?pr=31

seems failed?

**Review by airMeng — COMMENTED** [review]
shall you check whether bestla itself solve all errors?

**Comment by VincyZhang** [comment]
> https://github.com/intel/neural-speed/actions/runs/7418532866/job/20186610889?pr=31
> 
> seems failed?

where?

**Comment by VincyZhang** [comment]
> shall you check whether bestla itself solve all errors?

How to check?

**Comment by airMeng** [comment]
> > https://github.com/intel/neural-speed/actions/runs/7418532866/job/20186610889?pr=31
> > seems failed?
> 
> where?

scroll to the last
image

**Comment by VincyZhang** [comment]
> > > https://github.com/intel/neural-speed/actions/runs/7418532866/job/20186610889?pr=31
> > > seems failed?
> > 
> > 
> > where?
> 
> scroll to the last image

@zhewang1-intc can you add error output for CI to detect?

**Review by zhewang1-intc — APPROVED** [review]

**Review by kevinintel — APPROVED** [review]

**Pull request merged**
