### PR TITLE
Add eps as a parameter to ne_norm function

### PR DESCRIPTION
**Pull request by aahouzi**
## Type of Change

- eps parameter is hardcoded to 1e-5 in the ne_norm function, and many models in the convert script look for rms_norm_eps while the model doesn't use RMS normalization or have bad naming compared to config.json file.
- This PR fixes the above issues for all models, and suggests a single norm_eps parameter for both RMS normalization or classic normalization.

## Description

- Same as above

## Expected Behavior & Potential Risk

- N/A

## How has this PR been tested?

- Works fine for all models 

## Dependency Change?

- N/A

### CODE REVIEW

**Review by zhenwei-intel — APPROVED** [review]

**Review by a32543254 — APPROVED** [review]
LGTM

**Comment by a32543254** [comment]
thanks for you contribution.
After this PR, we could adopt Rms eps and Layernorm eps as one args.
could you kindly also check the  Format Scan  ?

**Comment by aahouzi** [comment]
@a32543254 all checks are passing now. However, it's little bit weird, since when I apply clang-format on the project directory for my modified files, it didn't pass the clangformat test. When I introduced the commit https://github.com/intel/neural-speed/pull/162/commits/7ea5623a6990925ae936109d1de458e4b57732de , it passed. Actually, I expect the .clang-format file to put everything in place or am I missing smthg here ?

**Comment by a32543254** [comment]
> @a32543254 all checks are passing now. However, it's little bit weird, since when I apply clang-format on the project directory for my modified files, it didn't pass the clangformat test. When I introduced the commit [7ea5623](https://github.com/intel/neural-speed/commit/7ea5623a6990925ae936109d1de458e4b57732de) , it passed. Actually, I expect the .clang-format file to put everything in place or am I missing smthg here ?

you can simple use clang-format.py in repo to auto check the clang format.
Everything is done by now. We will merge this pr soon

**Pull request merged**
