### PR TITLE
[LLM Runtime] Support the GGUF format

### PR DESCRIPTION
**Pull request by Zhenzhong1**
## Type of Change

New features add.

Verified models:

- [chatglm-2](https://huggingface.co/THUDM/chatglm-6b)
- [Llama-2](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf)

This PR paves the way for extending the GGUF format to all models in NeuralSpeed.

For example:
```python
# The only usage difference is to specify the GGUF by `--format=GGUF` when converting.
python scripts/convert_chatglm.py /root/zhenzhong/models/chatglm2-6b --outfile=ne-chatglm2-fp32.bin --outtype=f32 --format=GGUF
```

## Description

* Add the GGUF format for ChatGLM2 & Llama2

fp32-model.gguf inferneces pass:
image

Quantization of Jblas pass:
image

Ne-q4_j-model.gguf infernece pass:
image

## Expected Behavior & Potential Risk

N/A

## How has this PR been tested?

CI & manual tests

## Dependency Change?

N/A

### CODE REVIEW

**Comment by VincyZhang** [comment]
https://inteltf-jenk.sh.intel.com/job/neural_speed_extension/12/

**Review by a32543254 — APPROVED** [review]
LGTM

**Review by zhenwei-intel — APPROVED** [review]

**Comment by zhenwei-intel** [comment]
can we load q4_0 gguf from llama.cpp?

**Comment by Zhenzhong1** [comment]
> can we load q4_0 gguf from llama.cpp?

Here it only supports the bin file we converted. We can't load the llama.cpp gguf file currently, but I will enable this feature in the next PR.

**Comment by hshen14** [comment]
> > can we load q4_0 gguf from llama.cpp?
> 
> Here it only supports the bin file we converted. We can't load the llama.cpp gguf file currently, but I will enable this feature in the next PR.

let's update the readme to allow users to use our feature.

**Comment by Zhenzhong1** [comment]
https://github.com/intel/neural-speed/pull/48

**Pull request merged**
